import type { MarketDataProvider, Stock } from "./types";

export const mockStocks: Stock[] = [
  {
    ticker: "FPT",
    companyName: "Tập đoàn FPT",
    sector: "Công nghệ",
    currentPrice: 112000,
    previousClose: 110500,
    dailyChangePercent: 1.36,
    peRatio: 21.4,
    marketCap: 145000000000000,
    description: "Doanh nghiệp công nghệ và dịch vụ số, dùng trong dữ liệu mô phỏng.",
    isActive: true,
  },
  {
    ticker: "VNM",
    companyName: "Vinamilk",
    sector: "Hàng tiêu dùng",
    currentPrice: 68500,
    previousClose: 69000,
    dailyChangePercent: -0.72,
    peRatio: 16.8,
    marketCap: 143000000000000,
    description: "Doanh nghiệp sữa và hàng tiêu dùng, dữ liệu chỉ để học tập.",
    isActive: true,
  },
  {
    ticker: "MWG",
    companyName: "Thế Giới Di Động",
    sector: "Bán lẻ",
    currentPrice: 61400,
    previousClose: 60200,
    dailyChangePercent: 1.99,
    peRatio: 24.1,
    marketCap: 89900000000000,
    description: "Chuỗi bán lẻ công nghệ và tiêu dùng, mô phỏng cho phòng luyện tập.",
    isActive: true,
  },
  {
    ticker: "HPG",
    companyName: "Tập đoàn Hòa Phát",
    sector: "Thép",
    currentPrice: 28900,
    previousClose: 29200,
    dailyChangePercent: -1.03,
    peRatio: 14.2,
    marketCap: 169000000000000,
    description: "Doanh nghiệp thép chu kỳ, phù hợp luyện phân tích ngành.",
    isActive: true,
  },
  {
    ticker: "VCB",
    companyName: "Vietcombank",
    sector: "Ngân hàng",
    currentPrice: 91200,
    previousClose: 90500,
    dailyChangePercent: 0.77,
    peRatio: 18.5,
    marketCap: 510000000000000,
    description: "Ngân hàng thương mại lớn, dữ liệu mô phỏng cho bài học tài chính.",
    isActive: true,
  },
  {
    ticker: "BID",
    companyName: "BIDV",
    sector: "Ngân hàng",
    currentPrice: 42600,
    previousClose: 43100,
    dailyChangePercent: -1.16,
    peRatio: 12.6,
    marketCap: 243000000000000,
    description: "Ngân hàng thương mại, dùng để so sánh ngành trong phần mô phỏng.",
    isActive: true,
  },
  {
    ticker: "CTG",
    companyName: "VietinBank",
    sector: "Ngân hàng",
    currentPrice: 35800,
    previousClose: 35000,
    dailyChangePercent: 2.29,
    peRatio: 10.9,
    marketCap: 193000000000000,
    description: "Cổ phiếu ngân hàng trong bộ dữ liệu mẫu.",
    isActive: true,
  },
  {
    ticker: "ACB",
    companyName: "Ngân hàng Á Châu",
    sector: "Ngân hàng",
    currentPrice: 27600,
    previousClose: 27400,
    dailyChangePercent: 0.73,
    peRatio: 8.7,
    marketCap: 128000000000000,
    description: "Ngân hàng tư nhân, phục vụ bài tập so sánh định giá.",
    isActive: true,
  },
  {
    ticker: "GAS",
    companyName: "PV GAS",
    sector: "Năng lượng",
    currentPrice: 78200,
    previousClose: 79000,
    dailyChangePercent: -1.01,
    peRatio: 17.3,
    marketCap: 181000000000000,
    description: "Doanh nghiệp khí, dữ liệu mô phỏng cho phân bổ ngành.",
    isActive: true,
  },
  {
    ticker: "VHM",
    companyName: "Vinhomes",
    sector: "Bất động sản",
    currentPrice: 43200,
    previousClose: 42800,
    dailyChangePercent: 0.93,
    peRatio: 9.8,
    marketCap: 188000000000000,
    description: "Bất động sản nhà ở, dữ liệu chỉ để mô phỏng.",
    isActive: true,
  },
  {
    ticker: "VIC",
    companyName: "Tập đoàn Vingroup",
    sector: "Tập đoàn đa ngành",
    currentPrice: 46800,
    previousClose: 47400,
    dailyChangePercent: -1.27,
    peRatio: 28.2,
    marketCap: 182000000000000,
    description: "Tập đoàn đa ngành, dùng trong bài tập rủi ro và luận điểm.",
    isActive: true,
  },
  {
    ticker: "MSN",
    companyName: "Tập đoàn Masan",
    sector: "Hàng tiêu dùng",
    currentPrice: 72400,
    previousClose: 71000,
    dailyChangePercent: 1.97,
    peRatio: 31.5,
    marketCap: 103000000000000,
    description: "Doanh nghiệp tiêu dùng, bán lẻ và tài nguyên, dữ liệu mẫu.",
    isActive: true,
  },
  {
    ticker: "VRE",
    companyName: "Vincom Retail",
    sector: "Bất động sản bán lẻ",
    currentPrice: 21800,
    previousClose: 22100,
    dailyChangePercent: -1.36,
    peRatio: 13.7,
    marketCap: 49500000000000,
    description: "Bất động sản bán lẻ, phục vụ luyện tập phân tích ngành.",
    isActive: true,
  },
  {
    ticker: "SSI",
    companyName: "Chứng khoán SSI",
    sector: "Chứng khoán",
    currentPrice: 34900,
    previousClose: 34200,
    dailyChangePercent: 2.05,
    peRatio: 19.9,
    marketCap: 52300000000000,
    description: "Công ty chứng khoán, dùng để học về ngành tài chính.",
    isActive: true,
  },
  {
    ticker: "VND",
    companyName: "Chứng khoán VNDirect",
    sector: "Chứng khoán",
    currentPrice: 19600,
    previousClose: 19900,
    dailyChangePercent: -1.51,
    peRatio: 15.4,
    marketCap: 23900000000000,
    description: "Công ty chứng khoán trong bộ dữ liệu mô phỏng.",
    isActive: true,
  },
  {
    ticker: "PNJ",
    companyName: "Vàng bạc Đá quý Phú Nhuận",
    sector: "Bán lẻ",
    currentPrice: 98200,
    previousClose: 97000,
    dailyChangePercent: 1.24,
    peRatio: 20.2,
    marketCap: 32200000000000,
    description: "Doanh nghiệp bán lẻ trang sức, dữ liệu học tập.",
    isActive: true,
  },
  {
    ticker: "REE",
    companyName: "Cơ điện lạnh REE",
    sector: "Cơ điện lạnh",
    currentPrice: 68400,
    previousClose: 68100,
    dailyChangePercent: 0.44,
    peRatio: 10.1,
    marketCap: 28100000000000,
    description: "Doanh nghiệp hạ tầng và cơ điện, mô phỏng phân bổ danh mục.",
    isActive: true,
  },
  {
    ticker: "GMD",
    companyName: "Gemadept",
    sector: "Logistics",
    currentPrice: 74800,
    previousClose: 73500,
    dailyChangePercent: 1.77,
    peRatio: 18.8,
    marketCap: 25600000000000,
    description: "Doanh nghiệp cảng và hậu cần, dữ liệu mẫu.",
    isActive: true,
  },
  {
    ticker: "FRT",
    companyName: "Bán lẻ FPT",
    sector: "Bán lẻ",
    currentPrice: 159000,
    previousClose: 157500,
    dailyChangePercent: 0.95,
    peRatio: 33.6,
    marketCap: 21700000000000,
    description: "Chuỗi bán lẻ công nghệ và dược phẩm, dùng trong phòng luyện tập.",
    isActive: true,
  },
  {
    ticker: "DGC",
    companyName: "Hóa chất Đức Giang",
    sector: "Hóa chất",
    currentPrice: 112500,
    previousClose: 111200,
    dailyChangePercent: 1.17,
    peRatio: 12.4,
    marketCap: 42700000000000,
    description: "Doanh nghiệp hóa chất, phục vụ luyện tập rủi ro ngành.",
    isActive: true,
  },
];

export const mockMarketDataProvider: MarketDataProvider = {
  async listStocks() {
    return mockStocks;
  },
  async getStockByTicker(ticker: string) {
    return (
      mockStocks.find((stock) => stock.ticker === ticker.toUpperCase()) ?? null
    );
  },
};
